openai_api_key: "your api key"
vector_embedding_model : "text-embedding-3-small"
semantic_chunking_embedding_model : "text-embedding-3-small"
embedding_similarity_threshold: 0.25
top_k_retrieved_chunks : 3